const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const net = require('node:net');
const http = require('node:http');
test('authentication, drafts, CRUD, persistence and private file protection', async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'amaba-test-'));
  const socket = net.createServer(); await new Promise(resolve => socket.listen(0, '127.0.0.1', resolve)); const port = socket.address().port; await new Promise(resolve => socket.close(resolve));
  process.env.PORT = String(port);
  process.env.AMABA_ADMIN_PASSWORD = 'test-password-123456';
  process.env.AMABA_DATA_FILE = path.join(dir, 'data.json');
  process.env.AMABA_SITE_URL = 'https://amaba.example';
  const server = require('../server');
  try {
    await new Promise(resolve => server.listening ? resolve() : server.once('listening', resolve));
    const base = `http://127.0.0.1:${port}`;
    const familyInput = { nome: 'Maria Silva', email: 'MARIA@example.com', perfil: 'mae', senha: 'senha-familia-123', consentimento: true };
    const familyRequest = (route, input, headers = {}) => fetch(base + '/api/familias/' + route, { method: 'POST', headers: { 'Content-Type': 'application/json', ...headers }, body: JSON.stringify(input) });
    assert.equal((await familyRequest('cadastro', { ...familyInput, consentimento: false })).status, 400);
    assert.equal((await familyRequest('cadastro', familyInput, { Origin: 'https://other.example' })).status, 403);
    const familyResponse = await familyRequest('cadastro', familyInput); assert.equal(familyResponse.status, 201);
    const familyCookie = familyResponse.headers.get('set-cookie').split(';')[0];
    const family = await familyResponse.json(); assert.equal(family.email, 'maria@example.com'); assert.equal(family.nome, 'Maria Silva');
    assert.equal((await fetch(base + '/api/admin/conteudo', { headers: { Cookie: familyCookie } })).status, 401);
    assert.equal((await fetch(base + '/api/familias/session', { headers: { Cookie: familyCookie } })).status, 200);
    assert.equal((await familyRequest('cadastro', familyInput)).status, 409);
    assert.equal((await familyRequest('login', { ...familyInput, senha: 'incorrect' })).status, 401);
    assert.equal((await familyRequest('login', familyInput)).status, 200);
    const intakeUrl = base + '/api/familias/acolhimento';
    const intakeHeaders = { Cookie: familyCookie, 'Content-Type': 'application/json', 'X-CSRF-Token': family.csrf };
    const intakeInput = { cidade: 'Balsas', uf: 'MA', telefone: '', canal: 'email', interesses: ['rede'], consentimento: true, maioridade: true };
    const putIntake = input => fetch(intakeUrl, { method: 'PUT', headers: intakeHeaders, body: JSON.stringify(input) });
    assert.equal((await fetch(intakeUrl)).status, 401);
    assert.equal((await fetch(intakeUrl, { method: 'PUT', headers: { Cookie: familyCookie }, body: JSON.stringify(intakeInput) })).status, 403);
    assert.equal((await putIntake({ ...intakeInput, consentimento: false })).status, 400);
    assert.equal((await putIntake({ ...intakeInput, maioridade: false })).status, 400);
    assert.equal((await putIntake({ ...intakeInput, diagnostico: 'dados sensiveis' })).status, 400);
    assert.equal((await putIntake({ ...intakeInput, canal: 'whatsapp' })).status, 400);
    assert.equal((await putIntake({ ...intakeInput, interesses: ['diagnostico'] })).status, 400);
    assert.equal((await putIntake(intakeInput)).status, 200);
    let intake = await (await fetch(intakeUrl, { headers: { Cookie: familyCookie } })).json();
    assert.equal(intake.acolhimento.cidade, 'Balsas'); assert.equal(intake.csrf, family.csrf);
    assert.equal(intake.acolhimento.consentimento.versao, 'acolhimento-2026-10-04');
    assert.equal(Math.round((Date.parse(intake.acolhimento.expiraEm) - Date.parse(intake.acolhimento.atualizadoEm)) / 86400000), 180);
    assert.equal((await putIntake({ ...intakeInput, cidade: 'São Luís' })).status, 200);
    assert.equal((await fetch(intakeUrl, { method: 'DELETE', headers: intakeHeaders })).status, 200);
    intake = await (await fetch(intakeUrl, { headers: { Cookie: familyCookie } })).json(); assert.equal(intake.acolhimento, null);
    assert.equal((await putIntake(intakeInput)).status, 200);
    const expiredUsers = JSON.parse(fs.readFileSync(path.join(dir, 'familias.json'), 'utf8'));
    expiredUsers[0].acolhimento.expiraEm = '2000-01-01T00:00:00.000Z';
    fs.writeFileSync(path.join(dir, 'familias.json'), JSON.stringify(expiredUsers));
    intake = await (await fetch(intakeUrl, { headers: { Cookie: familyCookie } })).json(); assert.equal(intake.acolhimento, null);
    assert.equal(JSON.parse(fs.readFileSync(path.join(dir, 'familias.json'), 'utf8'))[0].acolhimento, undefined);
    assert.equal((await fetch(base + '/acolhimento.html')).status, 200);
    assert.equal((await familyRequest('logout', {}, { Cookie: familyCookie })).status, 403);
    assert.equal((await familyRequest('logout', {}, { Cookie: familyCookie, 'X-CSRF-Token': family.csrf })).status, 200);
    assert.equal((await fetch(base + '/api/familias/session', { headers: { Cookie: familyCookie } })).status, 401);
    const savedFamily = JSON.parse(fs.readFileSync(path.join(dir, 'familias.json'), 'utf8'))[0]; assert.ok(savedFamily.hash); assert.equal(savedFamily.senha, undefined);
    for (const page of ['login.html', 'cadastro.html', 'minha-conta.html']) assert.equal((await fetch(base + '/' + page)).status, 200);
    assert.equal((await fetch(base + '/api/admin/conteudo')).status, 401);
    assert.equal((await fetch(base + '/server.js')).status, 404);
    assert.equal((await fetch(base + '/data/conteudo.json')).status, 404);
    assert.equal((await fetch(base + '/admin.html')).status, 200);
    const missingPage = await fetch(base + '/nao-existe'); assert.equal(missingPage.status, 404); assert.match(await missingPage.text(), /Ir para o início/);
    let response = await fetch(base + '/api/login', { method: 'POST', body: JSON.stringify({ senha: 'wrong' }) }); assert.equal(response.status, 401);
    response = await fetch(base + '/api/login', { method: 'POST', body: JSON.stringify({ senha: 'test-password-123456' }) }); assert.equal(response.status, 200);
    const cookie = response.headers.get('set-cookie').split(';')[0], { csrf } = await response.json();
    const headers = { Cookie: cookie, 'Content-Type': 'application/json', 'X-CSRF-Token': csrf };
    assert.equal((await fetch(base + '/api/admin/publicacoes', { method: 'POST', headers: { Cookie: cookie }, body: '{}' })).status, 403);
    assert.equal((await fetch(base + '/api/admin/publicacoes', { method: 'POST', headers: { ...headers, Origin: 'https://other.example' }, body: '{}' })).status, 403);
    const item = { titulo: 'Teste', resumo: 'Resumo', data: '2026-10-03', tipo: 'noticia', publicado: false, paragrafos: ['Texto'], revisao: 1 };
    assert.equal((await fetch(base + '/api/admin/publicacoes', { method: 'POST', headers, body: JSON.stringify(item) })).status, 200);
    assert.equal((await (await fetch(base + '/api/conteudo')).json()).publicacoes.length, 0);
    const delayed = http.request(base + '/api/admin/publicacoes', { method: 'POST', headers }, response => response.resume());
    delayed.write('{"titulo":');
    const delayedDone = new Promise((resolve, reject) => { delayed.on('response', response => response.on('end', () => resolve(response.statusCode))); delayed.on('error', reject); });
    await new Promise(resolve => setTimeout(resolve, 30));
    assert.equal((await fetch(base + '/api/admin/publicacoes', { method: 'POST', headers, body: JSON.stringify({ ...item, titulo: 'Simultâneo' }) })).status, 200);
    delayed.end(JSON.stringify({ ...item, titulo: 'Lento' }).slice('{"titulo":'.length));
    assert.equal(await delayedDone, 200);
    let concurrent = await (await fetch(base + '/api/admin/conteudo', { headers })).json(); assert.equal(concurrent.publicacoes.length, 3);
    for (const record of concurrent.publicacoes.filter(p => p.titulo !== 'Teste')) await fetch(base + '/api/admin/publicacoes/' + record.id, { method: 'DELETE', headers });
    let data = await (await fetch(base + '/api/admin/conteudo', { headers })).json(); const id = data.publicacoes[0].id;
    assert.equal(JSON.parse(fs.readFileSync(path.join(dir, 'data.json'))).publicacoes[0].id, id);
    assert.equal((await fetch(base + '/api/admin/publicacoes/' + id, { method: 'PUT', headers, body: JSON.stringify({ ...item, publicado: true }) })).status, 200);
    assert.equal((await fetch(base + '/api/admin/publicacoes/' + id, { method: 'PUT', headers, body: JSON.stringify({ ...item, publicado: true }) })).status, 409);
    assert.equal((await (await fetch(base + '/api/conteudo')).json()).publicacoes[0].titulo, 'Teste');
    const rendered = await fetch(base + '/postagem.html?id=' + id); assert.equal(rendered.status, 200); const html = await rendered.text(); assert.match(html, /<h1>Teste<\/h1>/); assert.match(html, /og:title/); assert.doesNotMatch(html, /Carregando publicação/);
    const listing = await (await fetch(base + '/postagens.html')).text(); assert.match(listing, /<h2>Teste<\/h2>/);
    assert.match(await (await fetch(base + '/sitemap.xml')).text(), /https:\/\/amaba.example\/postagem.html/);
    assert.match(await (await fetch(base + '/robots.txt')).text(), /Disallow: \/admin.html/);
    assert.equal((await fetch(base + '/postagem.html?id=inexistente')).status, 404);
    const { renderDetail } = require('../public-view');
    const safe = renderDetail(fs.readFileSync(path.join(__dirname, '..', 'postagem.html'), 'utf8'), { ...item, titulo: '<script>alert(1)</script> $&', resumo: '" onload="bad', paragrafos: ['<img src=x onerror=bad>'] }, 'publicacoes');
    assert.match(safe, /&lt;script&gt;/); assert.match(safe, /\$&/); assert.doesNotMatch(safe, /<script>alert/); assert.doesNotMatch(safe, /<img src=x/);
    assert.equal((await fetch(base + '/api/admin/publicacoes', { method: 'POST', headers, body: JSON.stringify({ ...item, data: '2026-02-30' }) })).status, 400);
    assert.equal((await fetch(base + '/api/admin/publicacoes', { method: 'POST', headers, body: JSON.stringify({ ...item, tipo: 'evento', publicado: true }) })).status, 400);
    assert.equal((await fetch(base + '/api/admin/upload', { method: 'POST', headers, body: JSON.stringify({ imagem: 'data:image/webp;base64,aGVsbG8=' }) })).status, 400);
    const encoded = fs.readFileSync(path.join(__dirname, '..', 'assets', 'foto-mae-filho.webp')).toString('base64');
    const uploadResponse = await fetch(base + '/api/admin/upload', { method: 'POST', headers, body: JSON.stringify({ imagem: 'data:image/webp;base64,' + encoded }) }); assert.equal(uploadResponse.status, 201);
    const uploaded = await uploadResponse.json(); assert.match(uploaded.path, /^assets\/upload-[a-f0-9-]+\.webp$/);
    try { assert.equal((await fetch(base + '/' + uploaded.path)).status, 200); } finally { fs.unlinkSync(path.join(__dirname, '..', uploaded.path)); }
    for (const collection of ['projetos','parceiros']) {
      assert.equal((await fetch(base + '/api/admin/' + collection, { method: 'POST', headers, body: JSON.stringify({ titulo: 'Projeto', nome: 'Parceiro', publicado: true }) })).status, 200);
      assert.equal((await (await fetch(base + '/api/conteudo')).json())[collection].length, 1);
    }
    const project = (await (await fetch(base + '/api/conteudo')).json()).projetos[0]; assert.match(await (await fetch(base + '/projeto.html?id=' + project.id)).text(), /<h1>Projeto<\/h1>/);
    assert.equal((await fetch(base + '/api/admin/usuarios', { method: 'POST', headers, body: JSON.stringify({ usuario: 'editora', role: 'editor', senha: 'editor-password-123456' }) })).status, 201);
    response = await fetch(base + '/api/login', { method: 'POST', body: JSON.stringify({ usuario: 'editora', senha: 'editor-password-123456' }) }); assert.equal(response.status, 200);
    const editorCookie = response.headers.get('set-cookie').split(';')[0]; assert.equal((await fetch(base + '/api/admin/usuarios', { headers: { Cookie: editorCookie } })).status, 403);
    assert.doesNotMatch(fs.readFileSync(path.join(dir, 'usuarios.json'), 'utf8'), /editor-password-123456/);
    assert.equal((await fetch(base + '/api/admin/usuarios/editora', { method: 'DELETE', headers })).status, 200);
    assert.equal((await fetch(base + '/api/admin/conteudo', { headers: { Cookie: editorCookie } })).status, 401);
    assert.equal((await fetch(base + '/api/admin/usuarios/admin', { method: 'DELETE', headers })).status, 400);
    const audit = await (await fetch(base + '/api/admin/auditoria', { headers })).json(); assert(audit.some(entry => entry.usuario === 'admin' && entry.acao === 'POST'));
    assert(fs.readdirSync(path.join(dir, 'backups')).length > 0);
    const restore = require('../scripts/restore'); const backup = path.join(dir, 'backups', fs.readdirSync(path.join(dir, 'backups'))[0]); const restored = path.join(dir, 'restored.json'); restore(backup, restored); assert.deepEqual(JSON.parse(fs.readFileSync(restored)), JSON.parse(fs.readFileSync(backup)));
    const before = fs.readFileSync(restored, 'utf8'); const invalidBackup = path.join(dir, 'invalid.json'); fs.writeFileSync(invalidBackup, '{}'); assert.throws(() => restore(invalidBackup, restored), /Backup inválido/); assert.equal(fs.readFileSync(restored, 'utf8'), before);
    assert.equal((await fetch(base + '/api/admin/senha', { method: 'POST', headers, body: JSON.stringify({ atual: 'test-password-123456', nova: 'new-password-123456' }) })).status, 200);
    response = await fetch(base + '/api/login', { method: 'POST', body: JSON.stringify({ senha: 'test-password-123456' }) }); assert.equal(response.status, 401);
    response = await fetch(base + '/api/login', { method: 'POST', body: JSON.stringify({ senha: 'new-password-123456' }) }); assert.equal(response.status, 200);
    assert.equal((await fetch(base + '/api/admin/parceiros', { method: 'POST', headers, body: JSON.stringify({ nome: 'Bad', url: 'javascript:alert(1)' }) })).status, 400);
    assert.equal((await fetch(base + '/api/admin/publicacoes/' + id, { method: 'DELETE', headers })).status, 200);
    assert.equal((await (await fetch(base + '/api/conteudo')).json()).publicacoes.length, 0);
    assert.equal((await fetch(base + '/api/logout', { method: 'POST', headers })).status, 200);
    assert.equal((await fetch(base + '/api/admin/conteudo', { headers })).status, 401);
  } finally { server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); fs.rmSync(dir, { recursive: true, force: true }); }
});
